### ISSUE TITLE
format in QR returned by banking apps

### ISSUE THREAD

**Issue by bsl** [ihiroshi27/promptpay-js#1]
Hi, sorry to bother you. When sending a Promptpay transfer with a banking app, the app usually saves a receipt containing a QR code. Do you know if the format of the data in the receipt QR is part of the Promptpay spec? So far it does not appear to be, because it does not seem to use tag bytes. Is that data some bank-specific format? Thank you.

**Comment by ihiroshi27** [comment]
Hi @bsl, the QR on the receipt is called Mini QR.
You have to integrate with the bank or payment provider to verify that QR.
it's not part of Promptpay spec.

**Comment by bsl** [comment]
Thank you!
